from pre_defined_answers import all_projects, all_certifications, all_qualifications, all_experience
all_project_questions = [
"Can you list his Projects?",
"list his Projects?",
"his Projects?",
"Projects?",
"His Projects?",
"Can you list Ankur's Projects?",
"Can you list Ankur's Projects?",
"Ankur's Projects?",
"Ankur's Projects?",
"What projects has Ankur worked on?",
"What projects has Ankur worked on?",
"What projects has he worked on?",
"Ankur worked on which projects?",
"Ankur worked on which projects?",
"He worked on which projects?",
"Which projects has Ankur worked on?",
"Which projects has Ankur worked on?",
"Which projects has he worked on?",
"Tell me about Ankur's projects",
"Tell me about Ankur's projects",
"Tell me about his projects",
"What are some of Ankur's past projects?",
"What are some of Ankur's past projects?",
"What are some of his past projects?",
"List all projects Ankur has worked on",
"List all projects Ankur has worked on",
"List all projects he has worked on",
"Can you provide details on Ankur's projects?",
"Can you provide details on Ankur's projects?",
"Can you provide details on his projects?",
"Can you provide details on projects?",
"provide details on projects?",
"Give me an overview of Ankur's projects",
"Give me an overview of Ankur's projects",
"Give me an overview of his projects",
"What kind of projects has Ankur worked on?",
"What kind of projects has Ankur worked on?",
"What kind of projects has he worked on?",
"Can you summarize Ankur's project experience?",
"Can you summarize Ankur's project experience?",
"Can you summarize his project experience?",
"What are Ankur's key projects?",
"What are Ankur's key projects?",
"What are his key projects?",
"Has Ankur worked on any notable projects?",
"Has Ankur worked on any notable projects?",
"Has he worked on any notable projects?",
"Show me Ankur's project portfolio",
"Show me Ankur's project portfolio",
"Show me his project portfolio.",
"What projects are in Ankur's portfolio?",
"What projects are in Ankur's portfolio?",
"What projects are in his portfolio?",
"Provide a list of Ankur's completed projects",
"Provide a list of Ankur's completed projects",
"Provide a list of his completed projects",
"list of Ankur's completed projects",
"list of Ankur's completed projects",
"list of his completed projects",
"tell me about your projects",
"tell me about projects",
"projects you have worked in",
"give me a list of projects you have worked on",
"can you tell me about any projects you have worked on?",
"can you tell me about any Ankur's project?",
"can you tell me about any Ankur's project?",
"can you tell me about his projects?",
"tell me about any projects you have worked on?",
"what are some of your projects?",
]

all_certification_questions = [
    "Can you list his certifications?",
    "List his certifications?",
    "His certifications?",
    "Certifications?",
    "His Certifications?",
    "Can you list Ankur's certifications?",
    "Can you list Ankur's certifications?",
    "Ankur's certifications?",
    "Ankur's certifications?",
    "What certifications does Ankur have?",
    "What certifications does Ankur have?",
    "What certifications does he have?",
    "Ankur holds which certifications?",
    "Ankur holds which certifications?",
    "He holds which certifications?",
    "Which certifications has Ankur earned?",
    "Which certifications has Ankur earned?",
    "Which certifications has he earned?",
    "Tell me about Ankur's certifications",
    "Tell me about Ankur's certifications",
    "Tell me about his certifications",
    "What are some of Ankur's professional certifications?",
    "What are some of Ankur's professional certifications?",
    "What are some of his professional certifications?",
    "List all certifications Ankur has obtained",
    "List all certifications Ankur has obtained",
    "List all certifications he has obtained",
    "Can you provide details on Ankur's certifications?",
    "Can you provide details on Ankur's certifications?",
    "Can you provide details on his certifications?",
    "Provide details on certifications?",
    "Give me an overview of Ankur's certifications",
    "Give me an overview of Ankur's certifications",
    "Give me an overview of his certifications",
    "What type of certifications does Ankur hold?",
    "What type of certifications does Ankur hold?",
    "What type of certifications does he hold?",
    "Can you summarize Ankur's certification history?",
    "Can you summarize Ankur's certification history?",
    "Can you summarize his certification history?",
    "What are Ankur's key certifications?",
    "What are Ankur's key certifications?",
    "What are his key certifications?",
    "Has Ankur earned any notable certifications?",
    "Has Ankur earned any notable certifications?",
    "Has he earned any notable certifications?",
    "Show me Ankur's certification portfolio",
    "Show me Ankur's certification portfolio",
    "Show me his certification portfolio",
    "What certifications are in Ankur's credentials?",
    "What certifications are in Ankur's credentials?",
    "What certifications are in his credentials?",
    "Provide a list of Ankur's professional certifications",
    "Provide a list of Ankur's professional certifications",
    "Provide a list of his professional certifications",
    "List of Ankur's completed certifications",
    "List of Ankur's completed certifications",
    "List of his completed certifications",
    "Tell me about your certifications",
    "Tell me about professional certifications",
    "Certifications you have earned",
    "Give me a list of certifications you have obtained",
    "Can you tell me about any certifications you've earned?",
    "Can you tell me about Ankur's certification achievements?",
    "Can you tell me about Ankur's certification achievements?",
    "Can you tell me about his certification achievements?",
    "What are some of your certifications?",
    "Does Ankur have any Scrum certifications?",
    "Has Ankur completed any machine learning certifications?",
    "What technology certifications does he possess?",
    "When did Ankur obtain his Salesforce certification?",
    "Which institutions issued Ankur's certifications?",
    "Are Ankur's certifications still valid?",
    "How many certifications does he currently hold?",
    "What's the most recent certification Ankur earned?",
    "Has Ankur renewed any expired certifications?",
    "Did Ankur receive any certification honors or distinctions?",
    "certificstions?",  # Intentional typo coverage
    "certificstions list?",
    "his certificstions?",
    "wat r his certs?",  # Text-speak variation
    "Ankur's certs?",
    "certs list?"
]

all_qualification_questions = [
    "Can you list his qualifications?",
    "List his qualifications?",
    "His qualifications?",
    "Qualifications?",
    "His Qualifications?",
    "Can you list Ankur's qualifications?",
    "Can you list Ankur's qualifications?",
    "Ankur's qualifications?",
    "Ankur's qualifications?",
    "What qualifications does Ankur have?",
    "What qualifications does Ankur have?",
    "What qualifications does he have?",
    "Ankur holds which qualifications?",
    "Ankur holds which qualifications?",
    "He holds which qualifications?",
    "Which qualifications has Ankur obtained?",
    "Which qualifications has Ankur obtained?",
    "Which qualifications has he obtained?",
    "Tell me about Ankur's educational background",
    "Tell me about Ankur's academic qualifications",
    "Tell me about his professional qualifications",
    "What are Ankur's academic credentials?",
    "What are Ankur's educational qualifications?",
    "What are his professional credentials?",
    "List all degrees Ankur has earned",
    "List all certifications Ankur has completed",
    "List all professional qualifications he possesses",
    "Can you provide details on Ankur's educational history?",
    "Can you provide details on Ankur's academic background?",
    "Can you provide details on his professional training?",
    "Provide details on qualifications?",
    "Give me an overview of Ankur's education",
    "Give me an overview of Ankur's credentials",
    "Give me an overview of his academic history",
    "What type of degrees does Ankur hold?",
    "What type of certifications does Ankur possess?",
    "What kind of professional training has he completed?",
    "Can you summarize Ankur's educational journey?",
    "Can you summarize Ankur's career qualifications?",
    "Can you summarize his academic achievements?",
    "What are Ankur's key credentials?",
    "What are Ankur's main qualifications?",
    "What are his primary certifications?",
    "Has Ankur earned any advanced degrees?",
    "Has Ankur completed any specialized training?",
    "Has he obtained any professional licenses?",
    "Show me Ankur's academic portfolio",
    "Show me Ankur's professional credentials",
    "Show me his educational certificates",
    "What qualifications are listed in Ankur's CV?",
    "What credentials are in Ankur's resume?",
    "What academic achievements are in his profile?",
    "Provide a list of Ankur's academic qualifications",
    "Provide a list of Ankur's professional certifications",
    "Provide a list of his completed trainings",
    "List of Ankur's educational milestones",
    "List of Ankur's career certifications",
    "List of his professional accomplishments",
    "Tell me about your educational background",
    "Tell me about professional qualifications",
    "Degrees you have earned",
    "Give me a list of credentials you possess",
    "Can you tell me about any advanced degrees you've earned?",
    "Can you tell me about Ankur's academic honors?",
    "Can you tell me about Ankur's professional licenses?",
    "Can you tell me about his technical certifications?",
    "What are some of your academic achievements?",
    "Does Ankur have any engineering degrees?",
    "Has Ankur completed any MBA program?",
    "What technical qualifications does he possess?",
    "When did Ankur obtain his bachelor's degree?",
    "Which universities did Ankur attend?",
    "Are Ankur's certifications internationally recognized?",
    "How many professional qualifications does he currently hold?",
    "What's the highest qualification Ankur has achieved?",
    "Has Ankur pursued any doctoral studies?",
    "Did Ankur receive any academic awards?",
    "qualifciation?",  # Common misspelling
    "qualifcation list?",  # Typo variation
    "his qualifcation?",  # Spelling error
    "wat r his quals?",  # Text-speak variation
    "Ankur's edu background?",
    "academic creds?",
    "list ur qualifications?",  # Informal phrasing
    "what skools did he go to?",  # Intentional misspelling
    "any degrees?",  # Ultra-short form
    "he got phd?",  # Colloquial phrasing
    "Ankur graduted from where?",
    "his collage details?"  # Common misspelling
]

all_experience_questions = [
    # Work Experience Variations
    "What is Ankur's Work Experience?",
    "What is Ankur's Work Experience?",
    "What is his Work Experience?",
    "Work Experience?",
    "Ankur's Work Expeirence?",
    "Ankur's Work Expeirence?",
    "his Work Expeirence?",
    "Can you list Ankur's Work Experience?",
    "Can you list Ankur's Work Experience?",
    "Can you list his Work Experience?",
    "Describe Ankur's Work Experience",
    "Describe Ankur's Work Experience",
    "Describe his Work Experience",
    "How much Work Experience does Ankur have?",
    "How much Work Experience does Ankur have?",
    "How much Work Experience does he have?",
    "Detail Ankur's Work Experience",
    "Detail Ankur's Work Experience",
    "Detail his Work Experience",
    "Tell me about Ankur's Work Experience",
    "Tell me about Ankur's Work Experience",
    "Tell me about his Work Experience",
    "What are the highlights of Ankur's Work Experience?",
    "What are the highlights of Ankur's Work Experience?",
    "What are the highlights of his Work Experience?",
    "How long has Ankur been working?",
    "How long has Ankur been working?",
    "How long has he been working?",
    
    # Professional Experience Variations
    "What is Ankur's Professional Experience?",
    "What is Ankur's Professional Experience?",
    "What is his Professional Experience?",
    "Professional Experience?",
    "Ankur's Professional Expeirence?",
    "Ankur's Professional Expeirence?",
    "his Professional Expeirence?",
    "Could you outline Ankur's Professional Experience?",
    "Could you outline Ankur's Professional Experience?",
    "Could you outline his Professional Experience?",
    "Summarize Ankur's Professional Experience",
    "Summarize Ankur's Professional Experience",
    "Summarize his Professional Experience",
    "What roles has Ankur held in his Professional Experience?",
    "What roles has Ankur held in his Professional Experience?",
    "What roles has he held in his Professional Experience?",
    "Explain Ankur's Professional Background",
    "Explain Ankur's Professional Background",
    "Explain his Professional Background",
    
    # Industry Experience Variations
    "What is Ankur's Industry Experience?",
    "What is Ankur's Industry Experience?",
    "What is his Industry Experience?",
    "Industry Experience?",
    "Ankur's Industry Expeirence?",
    "Ankur's Industry Expeirence?",
    "his Industry Expeirence?",
    "Which industries has Ankur worked in?",
    "Which industries has Ankur worked in?",
    "Which industries has he worked in?",
    "What sectors does Ankur have experience in?",
    "What sectors does Ankur have experience in?",
    "What sectors does he have experience in?",
    "Describe Ankur's Industry Background",
    "Describe Ankur's Industry Background",
    "Describe his Industry Background",
    
    # Work History/Background Variations
    "What is Ankur's Work History?",
    "What is Ankur's Work History?",
    "What is his Work History?",
    "Work History?",
    "Ankur's Work History?",
    "Ankur's Work History?",
    "his Work History?",
    "What companies has Ankur worked for?",
    "What companies has Ankur worked for?",
    "What companies has he worked for?",
    "Where has Ankur worked before?",
    "Where has Ankur worked before?",
    "Where has he worked before?",
    "What is Ankur's Employment History?",
    "What is Ankur's Employment History?",
    "What is his Employment History?",
    
    # Career Experience & Skills
    "What is Ankur's Career Experience?",
    "What is Ankur's Career Experience?",
    "What is his Career Experience?",
    "Career Experience?",
    "What skills has Ankur gained from his experience?",
    "What skills has Ankur gained from his experience?",
    "What skills has he gained from his experience?",
    "What are Ankur's key career achievements?",
    "What are Ankur's key career achievements?",
    "What are his key career achievements?",
    "What responsibilities has Ankur handled?",
    "What responsibilities has Ankur handled?",
    "What responsibilities has he handled?",
    
    # Duration & Progression
    "How many years of experience does Ankur have?",
    "How many years of experience does Ankur have?",
    "How many years of experience does he have?",
    "How did Ankur start his career?",
    "How did Ankur start his career?",
    "How did he start his career?",
    "What is Ankur's career progression?",
    "What is Ankur's career progression?",
    "What is his career progression?",
    
    # Informal/Alternative Phrasings
    "Tell me about Ankur's work background",
    "Tell me about Ankur's work background",
    "Tell me about his work background",
    "What's Ankur's work story?",
    "What's Ankur's work story?",
    "What's his work story?",
    "Got any details on Ankur's experience?",
    "Got any details on Ankur's experience?",
    "Got any details on his experience?",
    "Walk me through Ankur's career",
    "Walk me through Ankur's career",
    "Walk me through his career",
    "What does Ankur do professionally?",
    "What does Ankur do professionally?",
    "What does he do professionally?",
]



dict = {}


for i in all_project_questions:
    dict[i] = all_projects

for i in all_certification_questions:
    dict[i] = all_certifications

for i in all_qualification_questions:
    dict[i] = all_qualifications

for i in all_experience_questions:
    dict[i] = all_experience

with open("stored_questions.py", "w") as file:
    file.write(f"var = {str(dict)}")